import React from 'react';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import { 
  Download, 
  Building, 
  TrendingUp, 
  Users, 
  DollarSign, 
  AlertTriangle, 
  CheckCircle, 
  Rocket,
  Brain,
  BarChart3,
  Crown,
  MapPin,
  Calendar
} from 'lucide-react';

const PDFExport = ({ startupData, onClose }) => {
  // Helper function to safely convert values to strings
  const safeString = (value, fallback = 'N/A') => {
    if (value === null || value === undefined) return fallback;
    if (typeof value === 'string') return value;
    if (typeof value === 'number') return value.toString();
    if (typeof value === 'boolean') return value ? 'Yes' : 'No';
    if (Array.isArray(value)) return value.join(', ');
    if (typeof value === 'object') return JSON.stringify(value);
    return String(value);
  };

  const generatePDF = async () => {
    try {
      const pdf = new jsPDF('p', 'mm', 'a4');
      const pageWidth = pdf.internal.pageSize.getWidth();
      const pageHeight = pdf.internal.pageSize.getHeight();
      const margin = 15;
      const contentWidth = pageWidth - 2 * margin;
      let currentPage = 1;
      
      // Helper function to add header to each page
      const addHeader = () => {
        pdf.setFillColor(25, 36, 82); // #192452
        pdf.rect(0, 0, pageWidth, 20, 'F');
        pdf.setTextColor(247, 255, 255); // white
        pdf.setFontSize(16);
        pdf.setFont('helvetica', 'bold');
        pdf.text('LetsAnalyse', margin, 14);
        pdf.setFontSize(9);
        pdf.setFont('helvetica', 'normal');
        pdf.text('Comprehensive Startup Analysis Report', pageWidth - margin - 65, 14);
        pdf.setTextColor(0, 0, 0); // reset to black
      };
      
      // Helper function to add footer
      const addFooter = () => {
        pdf.setFontSize(7);
        pdf.setTextColor(107, 114, 128);
        pdf.text(`Generated by LetsAnalyse • ${new Date().toLocaleDateString()} • Page ${currentPage}`, margin, pageHeight - 8);
        pdf.setTextColor(0, 0, 0);
        currentPage++;
      };
      
      // Helper function to add section title
      const addSectionTitle = (title, yPos, color = [25, 36, 82]) => {
        pdf.setFillColor(...color);
        pdf.rect(margin, yPos, contentWidth, 8, 'F');
        pdf.setTextColor(247, 255, 255);
        pdf.setFontSize(12);
        pdf.setFont('helvetica', 'bold');
        pdf.text(title, margin + 3, yPos + 6);
        pdf.setTextColor(0, 0, 0);
        return yPos + 12;
      };
      
      let yPos = 35;
      
      // PAGE 1: Company Overview
      addHeader();
      
      // Company header with investment score
      pdf.setFillColor(248, 250, 252);
      pdf.rect(margin, yPos, contentWidth, 40, 'F');
      pdf.setFillColor(8, 206, 107);
      pdf.rect(pageWidth - margin - 50, yPos + 5, 40, 30, 'F');
      
      pdf.setTextColor(247, 255, 255);
      pdf.setFontSize(16);
      pdf.setFont('helvetica', 'bold');
      pdf.text(`${safeString(startupData.investmentScore, '8.7')}/10`, pageWidth - margin - 30, yPos + 18);
      pdf.setFontSize(8);
      pdf.text('Score', pageWidth - margin - 30, yPos + 25);
      
      pdf.setTextColor(25, 36, 82);
      pdf.setFontSize(20);
      pdf.text(safeString(startupData.name, 'Company Name'), margin + 5, yPos + 15);
      pdf.setFontSize(12);
      pdf.setTextColor(107, 114, 128);
      pdf.text(safeString(startupData.tagline, 'Company tagline'), margin + 5, yPos + 25);
      pdf.setFontSize(10);
      pdf.text(`📍 ${safeString(startupData.location, 'Location')} • 📅 Founded ${safeString(startupData.founded, '2020')} • 👥 ${safeString(startupData.employees, '50')} employees`, margin + 5, yPos + 35);
      
      yPos += 50;
      
      // Key Metrics
      pdf.setTextColor(25, 36, 82);
      pdf.setFontSize(16);
      pdf.setFont('helvetica', 'bold');
      pdf.text('Key Metrics', margin, yPos);
      yPos += 10;
      
      const metrics = [
        { label: 'ARR', value: safeString(startupData.keyMetrics?.arr, '$2.8M'), growth: safeString(startupData.keyMetrics?.arrGrowth, '+220%') },
        { label: 'Customers', value: safeString(startupData.keyMetrics?.customers, '1,450'), growth: safeString(startupData.keyMetrics?.customerGrowth, '+65%') },
        { label: 'Runway', value: safeString(startupData.keyMetrics?.runway, '22 mo'), growth: safeString(startupData.keyMetrics?.runwayChange, '+4mo') },
        { label: 'CAC', value: safeString(startupData.keyMetrics?.cac, '$420'), growth: safeString(startupData.keyMetrics?.cacChange, '-18%') }
      ];
      
      metrics.forEach((metric, i) => {
        const x = margin + (i % 2) * (contentWidth / 2);
        const y = yPos + Math.floor(i / 2) * 25;
        
        pdf.setFillColor(249, 250, 251);
        pdf.rect(x, y, contentWidth / 2 - 5, 20, 'F');
        pdf.setTextColor(107, 114, 128);
        pdf.setFontSize(8);
        pdf.text(safeString(metric.label), x + 5, y + 8);
        pdf.setTextColor(25, 36, 82);
        pdf.setFontSize(12);
        pdf.setFont('helvetica', 'bold');
        pdf.text(safeString(metric.value), x + 5, y + 14);
        pdf.setTextColor(8, 206, 107);
        pdf.setFontSize(8);
        pdf.text(safeString(metric.growth), x + 60, y + 14);
      });
      
      yPos += 60;
      
      // AI Investment Summary
      pdf.setTextColor(25, 36, 82);
      pdf.setFontSize(16);
      pdf.setFont('helvetica', 'bold');
      pdf.text('AI Investment Summary', margin, yPos);
      yPos += 10;
      
      pdf.setFillColor(239, 246, 255);
      pdf.rect(margin, yPos, contentWidth, 30, 'F');
      pdf.setTextColor(0, 0, 0);
      pdf.setFontSize(10);
      pdf.setFont('helvetica', 'normal');
      const summaryText = safeString(startupData.aiSummary?.investmentThesis, 'Strong growth metrics with healthy unit economics. Proven leadership team and solid product-market fit in the AI automation space.');
      const summaryLines = pdf.splitTextToSize(summaryText, contentWidth - 10);
      pdf.text(summaryLines, margin + 5, yPos + 8);
      
      addFooter(1);
      
      // PAGE 2: Competitor Analysis & Risk Assessment
      pdf.addPage();
      addHeader();
      yPos = 35;
      
      // Competitor Analysis
      pdf.setTextColor(25, 36, 82);
      pdf.setFontSize(16);
      pdf.setFont('helvetica', 'bold');
      pdf.text('Competitor Analysis', margin, yPos);
      yPos += 15;
      
      const competitors = startupData.competitorAnalysis || [
        { name: 'AutomateFlow Pro', funding: '$15M', valuation: '$80M', strengths: ['Market leader', 'Strong brand'] },
        { name: 'WorkflowAI', funding: '$8M', valuation: '$45M', strengths: ['Technical expertise', 'Fast growth'] }
      ];
      
      competitors.slice(0, 3).forEach((competitor, i) => {
        pdf.setFillColor(248, 250, 252);
        pdf.rect(margin, yPos, contentWidth, 25, 'F');
        
        pdf.setTextColor(25, 36, 82);
        pdf.setFontSize(12);
        pdf.setFont('helvetica', 'bold');
        pdf.text(safeString(competitor.name, 'Competitor'), margin + 5, yPos + 8);
        
        pdf.setTextColor(107, 114, 128);
        pdf.setFontSize(9);
        pdf.text(`Funding: ${safeString(competitor.funding, 'N/A')} • Valuation: ${safeString(competitor.valuation, 'N/A')}`, margin + 5, yPos + 15);
        
        if (competitor.strengths) {
          const strengthsText = Array.isArray(competitor.strengths) ? competitor.strengths.join(', ') : safeString(competitor.strengths);
          pdf.text(`Strengths: ${strengthsText}`, margin + 5, yPos + 20);
        }
        
        yPos += 30;
      });
      
      // Risk Assessment
      pdf.setTextColor(25, 36, 82);
      pdf.setFontSize(16);
      pdf.setFont('helvetica', 'bold');
      pdf.text('Risk Assessment', margin, yPos);
      yPos += 15;
      
      const risks = startupData.riskAssessment || [
        { type: 'Financial', issue: 'High customer concentration', severity: 'High', mitigation: 'Diversify customer base' },
        { type: 'Market', issue: 'Increasing competition', severity: 'Medium', mitigation: 'Strengthen differentiation' },
        { type: 'Technical', issue: 'Third-party dependencies', severity: 'Medium', mitigation: 'Build internal capabilities' }
      ];
      
      risks.slice(0, 4).forEach((risk, i) => {
        const severity = safeString(risk.severity, 'Medium');
        const severityColor = severity === 'High' ? [239, 68, 68] : severity === 'Medium' ? [245, 158, 11] : [34, 197, 94];
        
        pdf.setFillColor(249, 250, 251);
        pdf.rect(margin, yPos, contentWidth, 20, 'F');
        
        pdf.setFillColor(...severityColor);
        pdf.rect(margin + 5, yPos + 3, 3, 14, 'F');
        
        pdf.setTextColor(25, 36, 82);
        pdf.setFontSize(10);
        pdf.setFont('helvetica', 'bold');
        pdf.text(`${safeString(risk.type, 'Risk')}: ${safeString(risk.issue, 'Risk description')}`, margin + 12, yPos + 8);
        
        pdf.setTextColor(107, 114, 128);
        pdf.setFontSize(8);
        pdf.text(`Severity: ${severity} • Mitigation: ${safeString(risk.mitigation, 'TBD')}`, margin + 12, yPos + 15);
        
        yPos += 25;
      });
      
      addFooter(2);
      
      // PAGE 3: Growth Potential & Financial Data
      pdf.addPage();
      addHeader();
      yPos = 35;
      
      // Growth Potential
      pdf.setTextColor(25, 36, 82);
      pdf.setFontSize(16);
      pdf.setFont('helvetica', 'bold');
      pdf.text('Growth Potential', margin, yPos);
      yPos += 15;
      
      // Growth Score
      pdf.setFillColor(243, 244, 246);
      pdf.rect(margin, yPos, contentWidth, 40, 'F');
      pdf.setTextColor(141, 81, 255);
      pdf.setFontSize(32);
      pdf.setFont('helvetica', 'bold');
      pdf.text(`${safeString(startupData.growthPotential?.score, '8.7')}/10`, margin + contentWidth/2 - 20, yPos + 25);
      pdf.setTextColor(107, 114, 128);
      pdf.setFontSize(10);
      pdf.text('Growth Potential Score', margin + contentWidth/2 - 25, yPos + 35);
      
      yPos += 50;
      
      // Growth Factors
      const growthFactors = startupData.growthPotential?.factors || [
        'Strong product-market fit',
        'Scalable business model',
        'Experienced team',
        'Large addressable market'
      ];
      
      pdf.setTextColor(25, 36, 82);
      pdf.setFontSize(12);
      pdf.setFont('helvetica', 'bold');
      pdf.text('Growth Factors:', margin, yPos);
      yPos += 10;
      
      growthFactors.slice(0, 6).forEach((factor, i) => {
        pdf.setTextColor(8, 206, 107);
        pdf.text('✓', margin + 5, yPos + (i * 8));
        pdf.setTextColor(0, 0, 0);
        pdf.setFontSize(9);
        pdf.text(safeString(factor), margin + 12, yPos + (i * 8));
      });
      
      yPos += growthFactors.length * 8 + 15;
      
      // Financial Highlights
      pdf.setTextColor(25, 36, 82);
      pdf.setFontSize(16);
      pdf.setFont('helvetica', 'bold');
      pdf.text('Financial Highlights', margin, yPos);
      yPos += 15;
      
      const financialMetrics = [
        { label: 'Revenue Growth', value: safeString(startupData.financialData?.revenueGrowth, '220% YoY') },
        { label: 'Gross Margin', value: safeString(startupData.financialData?.grossMargin, '78%') },
        { label: 'Burn Rate', value: safeString(startupData.financialData?.burnRate, '$180K/month') },
        { label: 'LTV/CAC Ratio', value: safeString(startupData.financialData?.ltvCacRatio, '4.2x') }
      ];
      
      financialMetrics.forEach((metric, i) => {
        const x = margin + (i % 2) * (contentWidth / 2);
        const y = yPos + Math.floor(i / 2) * 15;
        
        pdf.setTextColor(107, 114, 128);
        pdf.setFontSize(9);
        pdf.text(safeString(metric.label) + ':', x, y);
        pdf.setTextColor(25, 36, 82);
        pdf.setFont('helvetica', 'bold');
        pdf.text(safeString(metric.value), x + 60, y);
        pdf.setFont('helvetica', 'normal');
      });
      
      addFooter(3);
      
      // Download the PDF
      pdf.save(`LetsAnalyse-Comprehensive-Analysis-${safeString(startupData.name, 'Startup').replace(/\s+/g, '-')}-${new Date().toISOString().split('T')[0]}.pdf`);
      
      // Close the modal
      onClose();
    } catch (error) {
      console.error('Error generating PDF:', error);
      alert('Error generating PDF. Please try again.');
    }
  };

  return (
    <div className="fixed inset-0 bg-black/50 backdrop-blur-sm flex items-center justify-center z-50 p-4">
      <div className="bg-gray-800 border border-gray-700 rounded-2xl max-w-md w-full p-6 shadow-2xl">
        <div className="flex items-center justify-between mb-6">
          <div className="flex items-center space-x-3">
            <div className="w-10 h-10 bg-gradient-to-br from-green-500 to-emerald-500 rounded-xl flex items-center justify-center">
              <Download className="text-white" size={20} />
            </div>
            <div>
              <h3 className="text-xl font-bold text-white">Export PDF Report</h3>
              <p className="text-sm text-gray-400">Generate comprehensive analysis</p>
            </div>
          </div>
          <button 
            onClick={onClose}
            className="text-gray-400 hover:text-white transition-colors"
          >
            ✕
          </button>
        </div>

        <div className="space-y-4 mb-6">
          <div className="bg-gray-700/50 p-4 rounded-xl border border-gray-600/50">
            <div className="flex items-center space-x-3 mb-3">
              <Building className="text-orange-400" size={16} />
              <span className="text-white font-semibold">Startup Overview</span>
            </div>
            <p className="text-gray-300 text-sm">Company details, metrics, and investment score</p>
          </div>

          <div className="bg-gray-700/50 p-4 rounded-xl border border-gray-600/50">
            <div className="flex items-center space-x-3 mb-3">
              <BarChart3 className="text-blue-400" size={16} />
              <span className="text-white font-semibold">Competitive Analysis</span>
            </div>
            <p className="text-gray-300 text-sm">Market positioning and competitor comparison</p>
          </div>

          <div className="bg-gray-700/50 p-4 rounded-xl border border-gray-600/50">
            <div className="flex items-center space-x-3 mb-3">
              <AlertTriangle className="text-red-400" size={16} />
              <span className="text-white font-semibold">Risk Assessment</span>
            </div>
            <p className="text-gray-300 text-sm">Key risks and mitigation strategies</p>
          </div>

          <div className="bg-gray-700/50 p-4 rounded-xl border border-gray-600/50">
            <div className="flex items-center space-x-3 mb-3">
              <Rocket className="text-purple-400" size={16} />
              <span className="text-white font-semibold">Growth Potential</span>
            </div>
            <p className="text-gray-300 text-sm">Growth score and investment recommendations</p>
          </div>
        </div>

        <div className="flex space-x-3">
          <button
            onClick={onClose}
            className="flex-1 px-4 py-3 bg-gray-700 hover:bg-gray-600 text-white rounded-xl font-semibold transition-all duration-300"
          >
            Cancel
          </button>
          <button
            onClick={generatePDF}
            className="flex-1 px-4 py-3 bg-gradient-to-r from-green-500 to-emerald-500 hover:from-green-600 hover:to-emerald-600 text-white rounded-xl font-semibold transition-all duration-300 hover:scale-105 hover:shadow-lg hover:shadow-green-500/25 flex items-center justify-center space-x-2"
          >
            <Download size={16} />
            <span>Generate PDF</span>
          </button>
        </div>

        <p className="text-xs text-gray-500 text-center mt-4">
          PDF will be downloaded directly to your device
        </p>
      </div>
    </div>
  );
};

export default PDFExport;
